<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="4">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1" startPos="0" endPos="0" selMode="0" lang="R" encoding="-1" filename="C:\Ecology\Drive\Research\ENMs - Predictor Inference\Scripts\02 Make Figures of Species and Landscapes.r" backupFilePath="" originalFileLastModifTimestamp="1558108782" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="7864439" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="6182" startPos="119" endPos="218" selMode="0" lang="R" encoding="-1" filename="C:\Ecology\Drive\Research\ENMs - Predictor Inference\Scripts\03 Make Figures of Results.r" backupFilePath="" originalFileLastModifTimestamp="1558108840" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="-1447104768" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="90" xOffset="0" scrollWidth="14066" startPos="2611" endPos="3488" selMode="0" lang="R" encoding="-1" filename="C:\Ecology\Drive\Research\ENMs - Predictor Inference\Scripts\SIMPLE BUG.r" backupFilePath="" originalFileLastModifTimestamp="1558132611" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="-1447104768" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="853" xOffset="0" scrollWidth="14066" startPos="42318" endPos="0" selMode="0" lang="R" encoding="-1" filename="C:\Ecology\Drive\Research\ENMs - Predictor Inference\Scripts\01 Run Scenarios.r" backupFilePath="" originalFileLastModifTimestamp="1558128912" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="-1447104768" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="134" xOffset="0" scrollWidth="14066" startPos="11486" endPos="11486" selMode="0" lang="R" encoding="-1" filename="C:\Ecology\Drive\R\enmSdmPredImport\R\predImportMakeData.r" backupFilePath="" originalFileLastModifTimestamp="1558132447" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="1145438208" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="35" xOffset="0" scrollWidth="14066" startPos="2280" endPos="2280" selMode="0" lang="R" encoding="-1" filename="C:\Ecology\Drive\R\enmSdm\R\sampleRast.r" backupFilePath="" originalFileLastModifTimestamp="1558131018" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="771751936" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="142" xOffset="0" scrollWidth="14066" startPos="8393" endPos="8393" selMode="0" lang="R" encoding="-1" filename="C:\Ecology\Drive\R\enmSdmPredImport\R\genesis.r" backupFilePath="" originalFileLastModifTimestamp="1558129243" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="6357038" mapWrapIndentMode="-1" mapIsWrap="no" />
        </mainView>
        <subView activeIndex="0" />
    </Session>
</NotepadPlus>
